apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: public.ecr.aws/p6g1c2o3/url-shortener:latest
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: "production"
            - name: SECRET_KEY_BASE
              value: "your_secret_key_here"
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener
spec:
  selector:
    app: url-shortener
  ports:
    - port: 80          # This is the port on which the service is exposed inside the cluster. Other pods within the cluster can access the service on this port.
      targetPort: 3000  # 3000  This specifies the port on the pod to which the service should forward traffic. This should match the port your application is listening on inside its container.
      nodePort: 30000   # node port
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: url-shortener
            port:
              number: 80
  